# Generated by Django 3.2.18 on 2023-03-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_no', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('emp_start_date', models.DateField()),
                ('emp_end_date', models.DateField()),
                ('photo', models.ImageField(upload_to='images')),
                ('status', models.TextField()),
            ],
        ),
    ]
